import { Skin, SkinId } from '../types/game';

export const SKINS: Record<SkinId, Skin> = {
  classic: {
    id: 'classic',
    name: 'Classic',
    price: 0,
    description: 'The iconic cyber runner equipped with retro photon visor.',
    suitColor: '#6366f1',
    visorColor: '#06b6d4',
    coreColor: '#38bdf8',
    helmetColor: '#1e293b',
    trailColor: '#38bdf8',
    accentBadge: 'OG',
  },
  neon: {
    id: 'neon',
    name: 'Neon',
    price: 50,
    description: 'Hyper-charged synthwave style with laser cyan and hot pink glow.',
    suitColor: '#ec4899',
    visorColor: '#22d3ee',
    coreColor: '#f472b6',
    helmetColor: '#0f172a',
    trailColor: '#f43f5e',
    accentBadge: 'NEON',
  },
  robot: {
    id: 'robot',
    name: 'Robot',
    price: 100,
    description: 'Polished titanium chassis with emerald matrix HUD display.',
    suitColor: '#64748b',
    visorColor: '#10b981',
    coreColor: '#34d399',
    helmetColor: '#334155',
    trailColor: '#10b981',
    accentBadge: 'BOT',
  },
  ninja: {
    id: 'ninja',
    name: 'Ninja',
    price: 150,
    description: 'Stealth shadow weave with crimson ocular sensor.',
    suitColor: '#18181b',
    visorColor: '#ef4444',
    coreColor: '#dc2626',
    helmetColor: '#09090b',
    trailColor: '#e11d48',
    accentBadge: 'SHADOW',
  },
  fire: {
    id: 'fire',
    name: 'Fire',
    price: 250,
    description: 'Ignited molten armor emitting solar flare jet exhaust.',
    suitColor: '#ea580c',
    visorColor: '#facc15',
    coreColor: '#f59e0b',
    helmetColor: '#7c2d12',
    trailColor: '#f97316',
    accentBadge: 'FLAME',
  },
  galaxy: {
    id: 'galaxy',
    name: 'Galaxy',
    price: 500,
    description: 'Forged from celestial stardust and pulsar energy.',
    suitColor: '#7e22ce',
    visorColor: '#38bdf8',
    coreColor: '#c084fc',
    helmetColor: '#3b0764',
    trailColor: '#d946ef',
    accentBadge: 'COSMIC',
  },
};

export const ALL_SKINS_LIST: Skin[] = Object.values(SKINS);
